spring:
  application:
    name: hft-service
  threads:
    virtual:
      enabled: true
server:
  port: 8080
  tomcat:
    threads:
      max: 200
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

hft:
  mode: LIVE
  risk:
    kill-switch: false
    max-order-notional-usd: 0
    max-order-size: 0
  strategy:
    midpoint-maker:
      enabled: false
      quote-size: 5
      spread: 0.01
      refresh-millis: 1000
  polymarket:
    clob-rest-url: https://clob.polymarket.com
    clob-ws-url: wss://ws-subscriptions-clob.polymarket.com
    chain-id: 137
    use-server-time: true
    market-ws-enabled: false
    market-asset-ids: [ ]
    auth:
      private-key: "REDACTED_POLYMARKET_PRIVATE_KEY"
      signature-type: 1
      funder-address: "0xd3d7ed6e3005dd6401be16fb6a4111d1b7fb2d19"
      api-key: "REDACTED_POLYMARKET_API_KEY"
      api-secret: "REDACTED_POLYMARKET_API_SECRET"
      api-passphrase: "REDACTED_POLYMARKET_API_PASSPHRASE"
      nonce: 0
      auto-create-or-derive-api-creds: false
